// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9g_3MTiHMLAxvc2Aj8mI0y1Bfjek4w2E',
    appId: '1:255634393046:web:29480fcbe8814ecfd48677',
    messagingSenderId: '255634393046',
    projectId: 'link-shortner-a76c8',
    authDomain: 'link-shortner-a76c8.firebaseapp.com',
    storageBucket: 'link-shortner-a76c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBElR8T2YuIIhZlYprox7nlosZUhRlRzaw',
    appId: '1:255634393046:android:8c39d3aaba736d39d48677',
    messagingSenderId: '255634393046',
    projectId: 'link-shortner-a76c8',
    storageBucket: 'link-shortner-a76c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANI9Wy-3qz5jyibLiIcQZEy-J7f-giP-M',
    appId: '1:255634393046:ios:906eda0d6bba9b83d48677',
    messagingSenderId: '255634393046',
    projectId: 'link-shortner-a76c8',
    storageBucket: 'link-shortner-a76c8.appspot.com',
    iosClientId:
        '255634393046-8cq0rot3ualp4dg1ad1molaeidnb4iek.apps.googleusercontent.com',
    iosBundleId: 'com.appgain.onlinepushertester',
  );
}
